# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Dependabot

on:
  workflow_dispatch:

permissions: {}

jobs:
  dependabot:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Dependabot
        uses: github/dependabot-action@c89b34c2902ced775b36011dcc9a1aec1d14b760 # v3.2.0
        with:
          github-token: ${{ github.token }}
